ARG REDIS_VERSION

FROM redis:${REDIS_VERSION}-alpine

RUN apk --update --no-cache add supervisor

COPY start.sh /start.sh
VOLUME /data
WORKDIR /

ENV CLUSTER_ANNOUNCE_IP 127.0.0.1

EXPOSE 7000 7001 7002 7003 7004 7005

CMD ["/start.sh"]
