name: Build
on: [push, pull_request]

env:
  IMAGE_NAME: tommy351/redis-cluster
  IMAGE_TEST_TAG: test

jobs:
  build:
    strategy:
      matrix:
        redis-version:
          - '6.0'
          - '5.0'
          - '4.0'
          - '3.2'
          - '3.0'
        image-distro:
          - ''
          - alpine
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set image context
        id: image
        run: |
          version='${{ matrix.redis-version }}'

          if [ -n '${{ matrix.image-distro }}' ]; then
            version="${version}-${{ matrix.image-distro }}"
          fi

          tags="${{ env.IMAGE_NAME }}:${version}"

          if [ '${{ matrix.redis-version }}' = '6.0' ]; then
            tags="${tags},${{ env.IMAGE_NAME }}:${{ matrix.image-distro || 'latest' }}"
          fi

          case '${{ matrix.redis-version }}' in
            '3.0' | '3.2')
              dockerfile=Dockerfile.3.x
              ;;
            '4.0')
              dockerfile=Dockerfile.4.x
              ;;
            *)
              dockerfile=Dockerfile.5.x
              ;;
          esac

          if [ -n '${{ matrix.image-distro }}' ]; then
            dockerfile="${dockerfile}-${{ matrix.image-distro }}"
          fi

          echo "::set-output name=file::$dockerfile"
          echo "::set-output name=tags::$tags"
          echo "::set-output name=args::REDIS_VERSION=${{ matrix.redis-version }}"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ steps.image.outputs.file }}
          build-args: ${{ steps.image.outputs.args }}
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TEST_TAG }}
      - name: Test Docker image
        run: docker-compose run --rm test
        if: ${{ !startsWith(matrix.redis-version, '3.') }}
        env:
          IMAGE_TAG: ${{ env.IMAGE_TEST_TAG }}
          REDIS_VERSION: ${{ matrix.redis-version }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ steps.image.outputs.file }}
          build-args: ${{ steps.image.outputs.args }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.image.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
