name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        redis-version:
          - '6.0'
          - '5.0'
          - '4.0'
          - '3.2'
          - '3.0'
        image-distro:
          - ''
          - alpine
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        with:
          platforms: arm64
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set image context
        id: image
        run: |
          image_name='tommy351/redis-cluster'
          context='${{ matrix.redis-version }}'

          if [ -n '${{ matrix.image-distro }}' ]; then
            context="${context}-${{ matrix.image-distro }}"
          fi

          tags="${image_name}:${context}"

          if [ '${{ matrix.redis-version }}' = '6.0' ]; then
            tags="${tags},${image_name}:${{ matrix.image-distro || 'latest' }}"
          fi

          echo "::set-output name=context::$context"
          echo "::set-output name=tags::$tags"
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.image.outputs.context }}
          load: true
          tags: tommy351/redis-cluster:test
      - name: Test Docker image
        run: docker-compose run --rm test
        if: ${{ !startsWith(matrix.redis-version, '3.') }}
        env:
          VERSION: test
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.image.outputs.context }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.image.outputs.tags }}
