name: Release
on:
  push:

jobs:
  release:
    strategy:
      matrix:
        redis-version:
          - '6.0'
          - '5.0'
          - '4.0'
          - '3.2'
          - '3.0'
        image-distro:
          - ''
          - alpine
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set image tag
        run: |
          version='${{ matrix.redis-version }}'

          if [ -n '${{ matrix.image-distro }}' ]; then
            version="${version}-${{ matrix.image-distro }}"
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV
      - name: Build Docker image
        run: docker-compose build redis-cluster
      - name: Push Docker image
        run: docker push tommy351/redis-cluster:${VERSION}
