name: Test
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        redis-version:
          - '6.0'
          - '5.0'
          - '4.0'
          - '3.2'
          - '3.0'
        image-distro:
          - ''
          - alpine
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set image tag
        run: |
          version='${{ matrix.redis-version }}'

          if [ -n '${{ matrix.image-distro }}' ]; then
            version="${version}-${{ matrix.image-distro }}"
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV
      - name: Build Docker image
        run: docker-compose build redis-cluster
      - name: Test Docker image
        run: docker-compose run --rm test
        if: ${{ !startsWith(matrix.redis-version, '3') }}
